# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communicate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ommunicate.proto\x12\tfl_server\"D\n\x06Weight\x12)\n\x0b\x61rr_of_arrs\x18\x01 \x03(\x0b\x32\x14.fl_server.InnerType\x12\x0f\n\x07\x66lag_id\x18\x02 \x01(\t\"\x18\n\tInnerType\x12\x0b\n\x03\x61rr\x18\x01 \x03(\x02\"\x17\n\x04\x66lag\x12\x0f\n\x07\x66lag_id\x18\x01 \x01(\t2\xae\x01\n\x02\x46L\x12\x36\n\x0cGetFlWeights\x12\x11.fl_server.Weight\x1a\x11.fl_server.Weight\"\x00\x12\x38\n\x10GetGlobalWeights\x12\x0f.fl_server.flag\x1a\x11.fl_server.Weight\"\x00\x12\x36\n\x10\x43ommunicatedText\x12\x0f.fl_server.flag\x1a\x0f.fl_server.flag\"\x00\x62\x06proto3')



_WEIGHT = DESCRIPTOR.message_types_by_name['Weight']
_INNERTYPE = DESCRIPTOR.message_types_by_name['InnerType']
_FLAG = DESCRIPTOR.message_types_by_name['flag']
Weight = _reflection.GeneratedProtocolMessageType('Weight', (_message.Message,), {
  'DESCRIPTOR' : _WEIGHT,
  '__module__' : 'communicate_pb2'
  # @@protoc_insertion_point(class_scope:fl_server.Weight)
  })
_sym_db.RegisterMessage(Weight)

InnerType = _reflection.GeneratedProtocolMessageType('InnerType', (_message.Message,), {
  'DESCRIPTOR' : _INNERTYPE,
  '__module__' : 'communicate_pb2'
  # @@protoc_insertion_point(class_scope:fl_server.InnerType)
  })
_sym_db.RegisterMessage(InnerType)

flag = _reflection.GeneratedProtocolMessageType('flag', (_message.Message,), {
  'DESCRIPTOR' : _FLAG,
  '__module__' : 'communicate_pb2'
  # @@protoc_insertion_point(class_scope:fl_server.flag)
  })
_sym_db.RegisterMessage(flag)

_FL = DESCRIPTOR.services_by_name['FL']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WEIGHT._serialized_start=32
  _WEIGHT._serialized_end=100
  _INNERTYPE._serialized_start=102
  _INNERTYPE._serialized_end=126
  _FLAG._serialized_start=128
  _FLAG._serialized_end=151
  _FL._serialized_start=154
  _FL._serialized_end=328
# @@protoc_insertion_point(module_scope)
