# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import communicate_pb2 as communicate__pb2


class FLStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFlWeights = channel.unary_unary(
                '/fl_server.FL/GetFlWeights',
                request_serializer=communicate__pb2.Weight.SerializeToString,
                response_deserializer=communicate__pb2.Weight.FromString,
                )
        self.GetGlobalWeights = channel.unary_unary(
                '/fl_server.FL/GetGlobalWeights',
                request_serializer=communicate__pb2.flag.SerializeToString,
                response_deserializer=communicate__pb2.Weight.FromString,
                )
        self.CommunicatedText = channel.unary_unary(
                '/fl_server.FL/CommunicatedText',
                request_serializer=communicate__pb2.flag.SerializeToString,
                response_deserializer=communicate__pb2.flag.FromString,
                )


class FLServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFlWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommunicatedText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFlWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlWeights,
                    request_deserializer=communicate__pb2.Weight.FromString,
                    response_serializer=communicate__pb2.Weight.SerializeToString,
            ),
            'GetGlobalWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalWeights,
                    request_deserializer=communicate__pb2.flag.FromString,
                    response_serializer=communicate__pb2.Weight.SerializeToString,
            ),
            'CommunicatedText': grpc.unary_unary_rpc_method_handler(
                    servicer.CommunicatedText,
                    request_deserializer=communicate__pb2.flag.FromString,
                    response_serializer=communicate__pb2.flag.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fl_server.FL', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FL(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFlWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fl_server.FL/GetFlWeights',
            communicate__pb2.Weight.SerializeToString,
            communicate__pb2.Weight.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGlobalWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fl_server.FL/GetGlobalWeights',
            communicate__pb2.flag.SerializeToString,
            communicate__pb2.Weight.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommunicatedText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fl_server.FL/CommunicatedText',
            communicate__pb2.flag.SerializeToString,
            communicate__pb2.flag.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
